name: Python package

on: [push]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python main.py
      - run: mkdir uploads
      - run: mv total.csv uploads
      - run: mv slushpool.json uploads
      - run: mv antpool.csv uploads
      - run: mv luxor.csv uploads
      - uses: actions/upload-artifact@v3
        with:
          name: downloads
          path: uploads
